# Generated by Django 5.2.5 on 2025-08-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdd_name', models.CharField(max_length=255)),
                ('cdd_position', models.CharField(choices=[('Telesales work from home', 'Telesales Wfh'), ('Telesales office', 'Telesales Office'), ('Trainer', 'Trainer'), ('Manager Marketing', 'Manager Marketing')], max_length=64)),
                ('cdd_tel', models.CharField(max_length=10)),
                ('cdd_resume', models.FileField(blank=True, null=True, upload_to='myapp/media/resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=64)),
                ('emp_username', models.CharField(max_length=64)),
                ('emp_password', models.CharField(max_length=64)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_position', models.CharField(choices=[('Telesales work from home', 'Telesales Wfh'), ('Telesales office', 'Telesales Office'), ('Trainer', 'Trainer'), ('Manager Marketing', 'Manager Marketing')], max_length=64)),
                ('emp_tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('job_subhead', models.CharField(max_length=255)),
                ('job_qualification', models.TextField()),
                ('job_benefit', models.TextField()),
                ('job_descriotion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=255)),
                ('news_subhead', models.CharField(max_length=255)),
                ('news_date', models.DateField(auto_now_add=True)),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='myapp/media/news_images/')),
                ('news_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_type', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('repair_problem', models.TextField()),
                ('repair_cause', models.TextField()),
                ('repair_location', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_img', models.ImageField(blank=True, null=True, upload_to='myapp/media/repair_report/')),
                ('repair_status', models.CharField(choices=[('กำลังดำเนินการ', 'In Progress'), ('ดำเนินการเรียบร้อย', 'Completed')], default='กำลังดำเนินการ', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='myapp.employee')),
            ],
        ),
    ]
