# Generated by Django 5.2.5 on 2025-09-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdd_name', models.CharField(max_length=255)),
                ('cdd_position', models.CharField(choices=[('Telesales work from home', 'Telesales Wfh'), ('Telesales office', 'Telesales Office'), ('Trainer', 'Trainer'), ('Manager Marketing', 'Manager Marketing')], max_length=64)),
                ('cdd_tel', models.CharField(max_length=10)),
                ('cdd_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('ข่าวประชาสัมพันธ์', 'Nesws Poster'), ('กิจกรรมบริษัท', 'Company Activity'), ('ข่าวสาร', 'News'), ('อื่น ๆ ', 'Other')], max_length=64)),
                ('job_subhead', models.TextField()),
                ('job_qualification', models.TextField()),
                ('job_benefit', models.TextField()),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=255)),
                ('news_subhead', models.CharField(max_length=255)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='new_images/')),
                ('news_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=64)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_position', models.CharField(choices=[('Telesales work from home', 'Telesales Wfh'), ('Telesales office', 'Telesales Office'), ('Trainer', 'Trainer'), ('Manager Marketing', 'Manager Marketing')], max_length=64)),
                ('emp_tel', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_type', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('repair_problem', models.TextField()),
                ('repair_cause', models.TextField()),
                ('repair_location', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_img', models.ImageField(blank=True, null=True, upload_to='repair_report/')),
                ('repair_status', models.CharField(choices=[('กำลังดำเนินการ', 'In Progress'), ('ดำเนินการเรียบร้อย', 'Completed')], default='กำลังดำเนินการ', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='myapp.employee')),
            ],
        ),
    ]
