# Generated by Django 5.2.5 on 2025-09-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdd_title', models.CharField(choices=[('MR', 'นาย'), ('MRS', 'นาง'), ('MS', 'นางสาว')], max_length=8, verbose_name='คำนำหน้า')),
                ('cdd_first_name', models.CharField(max_length=128, verbose_name='ชื่อจริง')),
                ('cdd_last_name', models.CharField(max_length=128, verbose_name='นามสกุล')),
                ('cdd_nickname', models.CharField(blank=True, max_length=64, verbose_name='ชื่อเล่น')),
                ('cdd_gender', models.CharField(choices=[('MALE', 'ชาย'), ('FEMALE', 'หญิง')], max_length=8, verbose_name='เพศ')),
                ('cdd_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('cdd_position', models.CharField(choices=[('WFH', 'Telesales work from home'), ('OFFICE', 'Telesales office'), ('TRAINER', 'Trainer'), ('MKT', 'Manager Marketing')], max_length=32, verbose_name='ตำแหน่งที่สนใจสมัคร')),
                ('work_exp', models.TextField(blank=True, verbose_name='ประสบการณ์ทำงาน (ระบุคร่าว ๆ)')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='วุฒิการศึกษา')),
                ('start_date_available', models.DateField(blank=True, null=True, verbose_name='วันที่สามารถเริ่มงานได้')),
                ('cdd_tel', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('cdd_email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('cdd_province', models.CharField(blank=True, max_length=100, verbose_name='จังหวัด')),
                ('cdd_resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume / CV')),
                ('has_pc', models.BooleanField(default=False, verbose_name='คอมพิวเตอร์ (Windows 10+)')),
                ('has_laptop', models.BooleanField(default=False, verbose_name='โน้ตบุ้ค (Windows 10+)')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_headphone', models.BooleanField(default=False, verbose_name='Headphone')),
                ('has_anydesk', models.BooleanField(default=False, verbose_name='Anydesk')),
                ('cdd_status', models.CharField(choices=[('approved', 'อ่านแล้ว'), ('pending', 'ยังไม่ได้อ่าน')], default='pending', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'ผู้สมัคร',
                'verbose_name_plural': 'ผู้สมัคร',
                'ordering': ['cdd_first_name', 'cdd_last_name'],
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('ข่าวประชาสัมพันธ์', 'Nesws Poster'), ('กิจกรรมบริษัท', 'Company Activity'), ('ข่าวสาร', 'News'), ('อื่น ๆ ', 'Other')], max_length=64)),
                ('job_subhead', models.TextField()),
                ('job_qualification', models.TextField()),
                ('job_benefit', models.TextField()),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=255)),
                ('news_subhead', models.CharField(max_length=255)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='new_images/')),
                ('news_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=64)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_position', models.CharField(choices=[('WFH', 'Telesales work from home'), ('OFFICE', 'Telesales office'), ('TRAINER', 'Trainer'), ('MKT', 'Manager Marketing')], max_length=64)),
                ('emp_tel', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_type', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('repair_problem', models.TextField()),
                ('repair_cause', models.TextField()),
                ('repair_location', models.CharField(choices=[('System repair', 'System Repair'), ('General repair', 'General Repair')], max_length=64)),
                ('repair_img', models.ImageField(blank=True, null=True, upload_to='repair_report/')),
                ('repair_status', models.CharField(choices=[('กำลังดำเนินการ', 'In Progress'), ('ดำเนินการเรียบร้อย', 'Completed')], default='กำลังดำเนินการ', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='myapp.employee')),
            ],
        ),
    ]
