# Generated by Django 5.2.5 on 2025-10-20 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=64, verbose_name='รหัสพนักงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=255, verbose_name='ชื่อ-นามสกุล'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_position',
            field=models.CharField(choices=[('WFH', 'Telesales work from home'), ('OFFICE', 'Telesales office'), ('TRAINER', 'Trainer'), ('MKT', 'Manager Marketing')], max_length=64, verbose_name='ตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_tel',
            field=models.CharField(max_length=10, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_location',
            field=models.CharField(choices=[('ชั้น 1 ห้องอาหาร', 'ชั้น 1 ห้องอาหาร'), ('ชั้น 2 ห้อง HR', 'ชั้น 2 ห้อง HR'), ('ชั้น 3 ห้องพนักงาน', 'ชั้น 3 ห้องพนักงาน'), ('ชั้น 1 ห้องนักศึกษาฝึกงาน', 'ชั้น 1 ห้องนักศึกษาฝึกงาน'), ('ชั้น 2 ห้องพักนักศึกษ', 'ชั้น 2 ห้องพักนักศึกษา'), ('ชั้น 3 ห้องผู้บริหาร', 'ชั้น 3 ห้องผู้บริหาร')], max_length=64),
        ),
    ]
