# Generated by Django 5.2.5 on 2025-10-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_emp_id_alter_employee_emp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.ImageField(blank=True, help_text='อัปโหลดภาพประกอบของตำแหน่งงาน (เช่น โปสเตอร์รับสมัคร)', null=True, upload_to='jobs/', verbose_name='โปสเตอร์/รูปประกอบ'),
        ),
    ]
